/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.CadastroController;
import controllers.FrameController;
import controllers.LoginController;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import vo.ClienteVO;

/**
 *
 * @author bruno.franco
 */
public class EditarPerfil extends javax.swing.JFrame {

    private final FrameController controller = new FrameController();
    private final CadastroController cadController = new CadastroController();
    private final LoginController loginController = new LoginController();

    /**
     * Creates new form Cadastro
     */
    public EditarPerfil() {
        initComponents();

        ClienteVO clienteVO = loginController.buscarClienteLogado();

        nome_txt.setText(clienteVO.getNome());
        sobrenome_txt.setText(clienteVO.getSobrenome());
        email_txt.setText(clienteVO.getEmail());
        cpf_txt.setText(clienteVO.getCpf());
        diaNasc_txt.setText(clienteVO.getDtNasc().substring(0, 2));
        mesNasc_txt.setText(clienteVO.getDtNasc().substring(3, 5));
        anoNasc_txt.setText(clienteVO.getDtNasc().substring(6, 10));
        if (clienteVO.getSexo().equals("Masculino")) {
            radioSexoMasc.setSelected(true);
            radioSexoFem.setSelected(false);
        } else {
            radioSexoFem.setSelected(true);
            radioSexoMasc.setSelected(false);
        }
        senha.setText (clienteVO.getSenha());
        confSenha.setText (clienteVO.getCnfSenha());
        rua_txt.setText(clienteVO.getRua());
        numero_txt.setText(clienteVO.getNumero());
        bairro_txt1.setText(clienteVO.getBairro());
        cep_txt.setText(clienteVO.getCep());
        complemento_txt.setText(clienteVO.getComplemento());
        cidade_txt.setText(clienteVO.getCidade());
        estado_txt.setText(clienteVO.getEstado());
        ptReferencia_txt.setText(clienteVO.getPtReferencia());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        bairro_txt = new javax.swing.JTextField();
        panelCadastro = new javax.swing.JPanel();
        title_lbl = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelSobre = new javax.swing.JLabel();
        nome_txt = new javax.swing.JTextField();
        sobrenome_txt = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cpf_txt = new javax.swing.JTextField();
        labelDtNasc = new javax.swing.JLabel();
        diaNasc_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mesNasc_txt = new javax.swing.JTextField();
        anoNasc_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        labelDtNasc1 = new javax.swing.JLabel();
        radioSexoMasc = new javax.swing.JRadioButton();
        radioSexoFem = new javax.swing.JRadioButton();
        labelSenha = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        labelConformarSenha = new javax.swing.JLabel();
        confSenha = new javax.swing.JPasswordField();
        btnEditarCadastro = new javax.swing.JButton();
        lstErros = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        labelRua = new javax.swing.JLabel();
        rua_txt = new javax.swing.JTextField();
        labelNumero = new javax.swing.JLabel();
        labelBairro = new javax.swing.JLabel();
        labelCEP = new javax.swing.JLabel();
        labelCidade = new javax.swing.JLabel();
        labelComplemento = new javax.swing.JLabel();
        labelPtReferencia = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        numero_txt = new javax.swing.JTextField();
        cep_txt = new javax.swing.JTextField();
        complemento_txt = new javax.swing.JTextField();
        cidade_txt = new javax.swing.JTextField();
        estado_txt = new javax.swing.JTextField();
        ptReferencia_txt = new javax.swing.JTextField();
        bairro_txt1 = new javax.swing.JTextField();

        bairro_txt.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCadastro.setBackground(new java.awt.Color(255, 255, 255));

        title_lbl.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        title_lbl.setForeground(new java.awt.Color(255, 0, 0));
        title_lbl.setText("My Plate");

        labelNome.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        labelNome.setText("Nome:");

        labelSobre.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        labelSobre.setText("Sobrenome:");

        nome_txt.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N

        sobrenome_txt.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N

        labelEmail.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        labelEmail.setText("Email:");

        email_txt.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel1.setText("CPF:");

        labelDtNasc.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        labelDtNasc.setText("Data de Nascimento:");

        diaNasc_txt.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N

        jLabel2.setText("/");

        mesNasc_txt.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N

        anoNasc_txt.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N

        jLabel3.setText("/");

        labelDtNasc1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        labelDtNasc1.setText("Sexo:");

        buttonGroupSexo.add(radioSexoMasc);
        radioSexoMasc.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        radioSexoMasc.setText("Masculino");

        buttonGroupSexo.add(radioSexoFem);
        radioSexoFem.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        radioSexoFem.setText("Feminino");

        labelSenha.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        labelSenha.setText("Senha:");

        senha.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N

        labelConformarSenha.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        labelConformarSenha.setText("Confrmar Senha:");

        confSenha.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N

        btnEditarCadastro.setBackground(new java.awt.Color(255, 0, 51));
        btnEditarCadastro.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        btnEditarCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCadastro.setText("Salvar");
        btnEditarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCadastroActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(255, 0, 0));
        btnVoltar.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        labelRua.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        labelRua.setText("Rua:");

        rua_txt.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N

        labelNumero.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        labelNumero.setText("Número:");

        labelBairro.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        labelBairro.setText("Bairro:");

        labelCEP.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        labelCEP.setText("CEP:");

        labelCidade.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        labelCidade.setText("Cidade:");

        labelComplemento.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        labelComplemento.setText("Complemento:");

        labelPtReferencia.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        labelPtReferencia.setText("Ponte de Referência:");

        labelEstado.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        labelEstado.setText("Estado:");

        numero_txt.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N

        cep_txt.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N

        complemento_txt.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N

        cidade_txt.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N

        estado_txt.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N

        ptReferencia_txt.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N

        bairro_txt1.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelCadastroLayout = new javax.swing.GroupLayout(panelCadastro);
        panelCadastro.setLayout(panelCadastroLayout);
        panelCadastroLayout.setHorizontalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnEditarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addComponent(labelDtNasc1)
                                .addGap(20, 20, 20)
                                .addComponent(radioSexoMasc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioSexoFem))
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addComponent(labelSobre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sobrenome_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cpf_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lstErros))
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar)
                        .addGap(257, 257, 257)
                        .addComponent(title_lbl))
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelCadastroLayout.createSequentialGroup()
                                        .addComponent(labelNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nome_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelCadastroLayout.createSequentialGroup()
                                        .addComponent(labelDtNasc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(diaNasc_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mesNasc_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(anoNasc_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelCadastroLayout.createSequentialGroup()
                                        .addComponent(labelEmail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelCadastroLayout.createSequentialGroup()
                                        .addComponent(labelSenha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(senha)))
                                .addGap(59, 59, 59)
                                .addComponent(labelConformarSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addComponent(labelEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(estado_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelPtReferencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ptReferencia_txt))
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelCadastroLayout.createSequentialGroup()
                                        .addComponent(labelComplemento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(complemento_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelBairro)
                                    .addGroup(panelCadastroLayout.createSequentialGroup()
                                        .addComponent(labelRua)
                                        .addGap(18, 18, 18)
                                        .addComponent(rua_txt)))
                                .addGap(18, 18, 18)
                                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCadastroLayout.createSequentialGroup()
                                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelCidade)
                                            .addComponent(labelCEP))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cep_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cidade_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panelCadastroLayout.createSequentialGroup()
                                        .addComponent(labelNumero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(numero_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(bairro_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelCadastroLayout.setVerticalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar)
                        .addGap(53, 53, 53)
                        .addComponent(lstErros))
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addComponent(title_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNome)
                            .addComponent(nome_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSobre)
                            .addComponent(sobrenome_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpf_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diaNasc_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDtNasc)
                            .addComponent(jLabel2)
                            .addComponent(mesNasc_txt)
                            .addComponent(jLabel3)
                            .addComponent(anoNasc_txt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSenha)
                            .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRua)
                            .addComponent(rua_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNumero)
                            .addComponent(numero_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelBairro)
                            .addComponent(bairro_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioSexoFem)
                            .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelDtNasc1)
                                .addComponent(radioSexoMasc)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelConformarSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCEP)
                            .addComponent(cep_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)))
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelComplemento)
                    .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(complemento_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCidade)
                        .addComponent(cidade_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstado)
                    .addComponent(estado_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPtReferencia)
                    .addComponent(ptReferencia_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addComponent(btnEditarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Valida se os dados do formulario estão preenchidos, caso algum campo esteja vazio, adiciona um erro a uma lista
     * @return List erros
     */
    private List validateCliente(){
        
        List<String> erros = new ArrayList<String>();
        if (nome_txt.getText().isEmpty() || nome_txt.getText() == null) {
            erros.add("Campo Nome não preenchido");
        }
        if (sobrenome_txt.getText().isEmpty() || sobrenome_txt.getText() == null) {
            erros.add("Campo Sobrenome não preenchido");
        }
        if (email_txt.getText().isEmpty() || email_txt.getText() == null) {
            erros.add("Campo Email não preenchido");
        }
        if (cpf_txt.getText().isEmpty() || cpf_txt.getText() == null) {
            erros.add("Campo Cpf não preenchido");
        }
        if (diaNasc_txt.getText().isEmpty() || diaNasc_txt.getText() == null) {
            erros.add("Campo Dia não preenchido");
        }
        if (mesNasc_txt.getText().isEmpty() || mesNasc_txt.getText() == null) {
            erros.add("Campo Mês não preenchido");
        }
        if (anoNasc_txt.getText().isEmpty() || anoNasc_txt.getText() == null) {
            erros.add("Campo Ano não preenchido");
        }
        if (senha.getPassword().length == 0 || senha.getPassword() == null) {
            erros.add("Campo Senha não preenchido");
        }
        if (confSenha.getPassword().length == 0 || confSenha.getPassword() == null) {
            erros.add("Campo Confirmar Senha não preenchido");
        }
        if (senha.getPassword().length != 0 || senha.getPassword() != null) {
            if (confSenha.getPassword().length != 0 || confSenha.getPassword() != null) {

                char[] snh = senha.getPassword();
                char[] confSnh = confSenha.getPassword();
                String snhStr = new String(snh);
                String confSnhStr = new String(confSnh);

                if (!snhStr.equals(confSnhStr)) {
                    erros.add("Campo Confirmar Senha inválido");
                }
            }
        }

        return erros;
    }
    
    /**
     * Salva os dados preenchidos no formulario de edição de cadastro e salva num objeto virtual
     * @param evt 
     */
    private void btnEditarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCadastroActionPerformed
        ClienteVO cliente = new ClienteVO();

        cliente.setNome(nome_txt.getText());
        cliente.setSobrenome(sobrenome_txt.getText());
        cliente.setEmail(email_txt.getText());
        cliente.setCpf(cpf_txt.getText());
        cliente.setDtNasc(diaNasc_txt.getText() + "/" + mesNasc_txt.getText() + "/" + anoNasc_txt.getText());
        if (radioSexoMasc.isSelected()) {
            cliente.setSexo(radioSexoMasc.getText());
        } else if (radioSexoFem.isSelected()) {
            cliente.setSexo(radioSexoFem.getText());
        }
        char[] snh = senha.getPassword();
        String strSenha = new String(snh);
        cliente.setSenha(strSenha);

        char[] confSnh = confSenha.getPassword();
        String snhconf = new String(confSnh);
        cliente.setCnfSenha(snhconf);  
        
        cliente.setRua(rua_txt.getText());
        cliente.setNumero(numero_txt.getText());
        cliente.setBairro(bairro_txt1.getText());
        cliente.setCep(cep_txt.getText());
        cliente.setComplemento(complemento_txt.getText());
        cliente.setCidade(cidade_txt.getText());
        cliente.setEstado(estado_txt.getText());
        cliente.setPtReferencia(ptReferencia_txt.getText());
        
        List erros = validateCliente();

        if (erros.isEmpty()) {
            cadController.editarCadatro(cliente);
            cadController.salvaDadosUsuarioLogado(cliente);

            controller.renderPerfil(this);
        } else {

            Iterator i = erros.iterator();

            if (i.hasNext()) {
                lstErros.setText(erros.get(0).toString());
                lstErros.setForeground(Color.red);
            }
        }
    }//GEN-LAST:event_btnEditarCadastroActionPerformed
    
    /**
     * retorna para a pagina do perfil
     * @param evt 
     */
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        controller.renderPerfil(this);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anoNasc_txt;
    private javax.swing.JTextField bairro_txt;
    private javax.swing.JTextField bairro_txt1;
    private javax.swing.JButton btnEditarCadastro;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JTextField cep_txt;
    private javax.swing.JTextField cidade_txt;
    private javax.swing.JTextField complemento_txt;
    private javax.swing.JPasswordField confSenha;
    private javax.swing.JTextField cpf_txt;
    private javax.swing.JTextField diaNasc_txt;
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField estado_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCEP;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelComplemento;
    private javax.swing.JLabel labelConformarSenha;
    private javax.swing.JLabel labelDtNasc;
    private javax.swing.JLabel labelDtNasc1;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelPtReferencia;
    private javax.swing.JLabel labelRua;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelSobre;
    private javax.swing.JLabel lstErros;
    private javax.swing.JTextField mesNasc_txt;
    private javax.swing.JTextField nome_txt;
    private javax.swing.JTextField numero_txt;
    private javax.swing.JPanel panelCadastro;
    private javax.swing.JTextField ptReferencia_txt;
    private javax.swing.JRadioButton radioSexoFem;
    private javax.swing.JRadioButton radioSexoMasc;
    private javax.swing.JTextField rua_txt;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField sobrenome_txt;
    private javax.swing.JLabel title_lbl;
    // End of variables declaration//GEN-END:variables
}
