/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.FrameController;
import controllers.LoginController;
import vo.ClienteVO;

/**
 *
 * @author bruno.franco
 */
public class Perfil extends javax.swing.JFrame {

    private final FrameController controller = new FrameController();
    private final LoginController loginController = new LoginController();

    /**
     * Creates new form Perfil
     */
    public Perfil() {
        initComponents();

        ClienteVO cliente = loginController.buscarClienteLogado();

        nomeUsuario.setText("Nome: " + cliente.getNomeCompleto());
        emailUsuario.setText("Email: " + cliente.getEmail());
        cpfUsuario.setText("CPF: " + cliente.getCpf());
        dtNascUsuario.setText("Data de Nascimento: " + cliente.getDtNasc());
        sexoUsuario.setText("Sexo: " + cliente.getSexo());
        ruaUser.setText("Rua: " + cliente.getRua());
        numUser.setText("Numero: " + cliente.getNumero());
        bairroUser.setText("Bairro: " + cliente.getBairro());
        cepUser.setText("CEP: " + cliente.getCep());
        complementoUser.setText("Complemento: " + cliente.getComplemento());
        cidadeUser.setText("Cidade: " + cliente.getCidade());
        estadoUser.setText("Estado: " + cliente.getEstado());
        ptReferenciaUser.setText("Ponto de Referência: " + cliente.getPtReferencia());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        perfilPAnel = new javax.swing.JPanel();
        title_lbl = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        userArea = new javax.swing.JPanel();
        nomeUsuario = new javax.swing.JLabel();
        emailUsuario = new javax.swing.JLabel();
        cpfUsuario = new javax.swing.JLabel();
        dtNascUsuario = new javax.swing.JLabel();
        sexoUsuario = new javax.swing.JLabel();
        editarPerfil = new javax.swing.JButton();
        ruaUser = new javax.swing.JLabel();
        cepUser = new javax.swing.JLabel();
        numUser = new javax.swing.JLabel();
        complementoUser = new javax.swing.JLabel();
        estadoUser = new javax.swing.JLabel();
        bairroUser = new javax.swing.JLabel();
        cidadeUser = new javax.swing.JLabel();
        ptReferenciaUser = new javax.swing.JLabel();
        histPedidosBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        perfilPAnel.setBackground(new java.awt.Color(255, 255, 255));

        title_lbl.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        title_lbl.setForeground(new java.awt.Color(255, 0, 0));
        title_lbl.setText("My Plate");

        btnHome.setBackground(new java.awt.Color(255, 0, 0));
        btnHome.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/008-home.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnPerfil.setBackground(new java.awt.Color(255, 0, 0));
        btnPerfil.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(255, 0, 0));
        btnSair.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/012-sign-out-option.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        userArea.setBackground(new java.awt.Color(255, 255, 255));
        userArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nomeUsuario.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        nomeUsuario.setText("Nome:");

        emailUsuario.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        emailUsuario.setText("Email:");

        cpfUsuario.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        cpfUsuario.setText("CPF:");

        dtNascUsuario.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        dtNascUsuario.setText("Data Nascimento:");

        sexoUsuario.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        sexoUsuario.setText("Sexo:");

        editarPerfil.setBackground(new java.awt.Color(255, 0, 0));
        editarPerfil.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        editarPerfil.setForeground(new java.awt.Color(255, 255, 255));
        editarPerfil.setText("Editar");
        editarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPerfilActionPerformed(evt);
            }
        });

        ruaUser.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        ruaUser.setText("Rua:");

        cepUser.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        cepUser.setText("CEP:");

        numUser.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        numUser.setText("N°:");

        complementoUser.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        complementoUser.setText("Complemento:");

        estadoUser.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        estadoUser.setText("Estado:");

        bairroUser.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        bairroUser.setText("Bairro:");

        cidadeUser.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        cidadeUser.setText("Cidade:");

        ptReferenciaUser.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        ptReferenciaUser.setText("Ponto de Referencia:");

        javax.swing.GroupLayout userAreaLayout = new javax.swing.GroupLayout(userArea);
        userArea.setLayout(userAreaLayout);
        userAreaLayout.setHorizontalGroup(
            userAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userAreaLayout.createSequentialGroup()
                        .addComponent(estadoUser)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(userAreaLayout.createSequentialGroup()
                        .addGroup(userAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userAreaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(editarPerfil))
                            .addGroup(userAreaLayout.createSequentialGroup()
                                .addGroup(userAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(userAreaLayout.createSequentialGroup()
                                        .addGroup(userAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cpfUsuario)
                                            .addComponent(dtNascUsuario)
                                            .addComponent(sexoUsuario)
                                            .addComponent(emailUsuario)
                                            .addComponent(bairroUser)
                                            .addComponent(cepUser))
                                        .addGap(307, 307, 307)
                                        .addGroup(userAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cidadeUser)
                                            .addComponent(complementoUser)
                                            .addComponent(ptReferenciaUser)
                                            .addComponent(numUser)))
                                    .addComponent(nomeUsuario)
                                    .addComponent(ruaUser))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        userAreaLayout.setVerticalGroup(
            userAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cpfUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dtNascUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sexoUsuario)
                .addGap(28, 28, 28)
                .addGroup(userAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruaUser)
                    .addComponent(numUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(complementoUser)
                    .addComponent(bairroUser))
                .addGroup(userAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userAreaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cepUser))
                    .addGroup(userAreaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(cidadeUser)))
                .addGap(18, 18, 18)
                .addGroup(userAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estadoUser)
                    .addComponent(ptReferenciaUser))
                .addGap(88, 88, 88)
                .addComponent(editarPerfil)
                .addContainerGap())
        );

        histPedidosBtn.setBackground(new java.awt.Color(255, 0, 0));
        histPedidosBtn.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        histPedidosBtn.setForeground(new java.awt.Color(255, 255, 255));
        histPedidosBtn.setText("Ver histórico de compras");
        histPedidosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histPedidosBtnActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Visualizar Favoritos");

        javax.swing.GroupLayout perfilPAnelLayout = new javax.swing.GroupLayout(perfilPAnel);
        perfilPAnel.setLayout(perfilPAnelLayout);
        perfilPAnelLayout.setHorizontalGroup(
            perfilPAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perfilPAnelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(perfilPAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, perfilPAnelLayout.createSequentialGroup()
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(title_lbl)
                        .addGap(232, 232, 232)
                        .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(perfilPAnelLayout.createSequentialGroup()
                        .addComponent(histPedidosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        perfilPAnelLayout.setVerticalGroup(
            perfilPAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perfilPAnelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(perfilPAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(userArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(perfilPAnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(histPedidosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(perfilPAnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(perfilPAnel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Realiza logoff do usuario
     * @param evt 
     */
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        controller.renderLogin(this);
    }//GEN-LAST:event_btnSairActionPerformed
    
    /**
     * retorna para a tela de Perfil do usuário
     * @param evt 
     */
    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        controller.renderPerfil(this);
    }//GEN-LAST:event_btnPerfilActionPerformed
    /**
     * retorna para Home
     * @param evt 
     */
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        controller.renderHome(this);
    }//GEN-LAST:event_btnHomeActionPerformed
    
    /**
     * renderiza tela de edição de dados do perfil
     * @param evt 
     */
    private void editarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPerfilActionPerformed
        controller.renderEditarPerfil(this);
    }//GEN-LAST:event_editarPerfilActionPerformed

    private void histPedidosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histPedidosBtnActionPerformed
        controller.renderVisualizarHistórico(this);
    }//GEN-LAST:event_histPedidosBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bairroUser;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel cepUser;
    private javax.swing.JLabel cidadeUser;
    private javax.swing.JLabel complementoUser;
    private javax.swing.JLabel cpfUsuario;
    private javax.swing.JLabel dtNascUsuario;
    private javax.swing.JButton editarPerfil;
    private javax.swing.JLabel emailUsuario;
    private javax.swing.JLabel estadoUser;
    private javax.swing.JButton histPedidosBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel nomeUsuario;
    private javax.swing.JLabel numUser;
    private javax.swing.JPanel perfilPAnel;
    private javax.swing.JLabel ptReferenciaUser;
    private javax.swing.JLabel ruaUser;
    private javax.swing.JLabel sexoUsuario;
    private javax.swing.JLabel title_lbl;
    private javax.swing.JPanel userArea;
    // End of variables declaration//GEN-END:variables
}
